# Generated by Django 3.2.6 on 2021-09-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('season', models.IntegerField(verbose_name='Temporada')),
                ('alt_title', models.CharField(max_length=150, verbose_name='Título en Ingles')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (título entre guiones)')),
                ('country', models.CharField(max_length=56, verbose_name='País')),
                ('date', models.IntegerField(verbose_name='Año')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Miniatura (225x125)')),
                ('portrait', models.ImageField(upload_to='', verbose_name='Portada (300x450)')),
                ('recommended', models.BooleanField(default=False, verbose_name='Recomendada?')),
                ('up_date', models.DateField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='movieapp.Genres', verbose_name='Generos')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['up_date'],
            },
        ),
        migrations.CreateModel(
            name='Caps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name='Episodio Numero')),
                ('url', models.CharField(max_length=300, verbose_name='URL Opción 1:')),
                ('url2', models.CharField(blank=True, max_length=300, verbose_name='URL Opción 2:')),
                ('url3', models.CharField(blank=True, max_length=300, verbose_name='URL Opción SubEng:')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriesapp.serie')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['no'],
            },
        ),
    ]
