# Generated by Django 3.2.6 on 2021-09-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caps',
            options={'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.AlterModelOptions(
            name='seasons',
            options={'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
        migrations.RemoveField(
            model_name='seasons',
            name='caps',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='season',
        ),
        migrations.AddField(
            model_name='caps',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seriesapp.seasons', verbose_name='Temporadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasons',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seriesapp.serie'),
            preserve_default=False,
        ),
    ]
