# Generated by Django 3.2.6 on 2021-09-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0003_auto_20210906_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caps',
            name='no',
            field=models.IntegerField(unique=True, verbose_name='Episodio Numero'),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='no',
            field=models.IntegerField(unique=True, verbose_name='Temporada Numero'),
        ),
    ]
