# Generated by Django 3.2.6 on 2021-09-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0004_auto_20210906_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caps',
            options={'ordering': ['no'], 'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.RemoveField(
            model_name='caps',
            name='season',
        ),
        migrations.AddField(
            model_name='serie',
            name='caps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seriesapp.caps'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Seasons',
        ),
    ]
