# Generated by Django 3.2.6 on 2021-09-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0005_auto_20210906_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='caps',
        ),
        migrations.AddField(
            model_name='caps',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seriesapp.serie'),
            preserve_default=False,
        ),
    ]
