# Generated by Django 3.2.6 on 2021-09-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0006_auto_20210906_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='season',
            field=models.IntegerField(default=1, verbose_name='Temporada'),
            preserve_default=False,
        ),
    ]
