# Generated by Django 3.2.6 on 2021-09-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0007_serie_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='caps_amount',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Capitulos'),
            preserve_default=False,
        ),
    ]
