# Generated by Django 3.2.6 on 2021-09-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0008_serie_caps_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='caps_amount',
        ),
    ]
