# Generated by Django 3.2.6 on 2021-09-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0009_remove_serie_caps_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caps',
            name='no',
            field=models.IntegerField(verbose_name='Episodio Numero'),
        ),
    ]
