# Generated by Django 3.2.6 on 2021-09-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Año')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Miniatura (220x215)')),
                ('portrait', models.ImageField(upload_to='', verbose_name='Portada (180x270)')),
                ('url', models.CharField(max_length=200, verbose_name='URL Iframe')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.genres', verbose_name='Generos')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
    ]
