# Generated by Django 3.2.6 on 2021-09-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('alt_title', models.CharField(max_length=150, verbose_name='Título en Ingles')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (título entre guiones)')),
                ('country', models.CharField(max_length=56, verbose_name='País')),
                ('date', models.IntegerField(verbose_name='Año')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Miniatura (225x125)')),
                ('portrait', models.ImageField(upload_to='', verbose_name='Portada (300x450)')),
                ('url', models.CharField(max_length=300, verbose_name='URL Opción 1:')),
                ('url2', models.CharField(blank=True, max_length=300, verbose_name='URL Opción 2:')),
                ('url3', models.CharField(blank=True, max_length=300, verbose_name='URL Opción SubEng:')),
                ('recommended', models.BooleanField(default=False, verbose_name='Recomendada?')),
                ('premiere', models.BooleanField(default=False, verbose_name='Estreno?')),
                ('up_date', models.DateField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='movieapp.Genres', verbose_name='Generos')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['up_date'],
            },
        ),
    ]
