# Generated by Django 3.2.6 on 2021-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('alt_title', models.CharField(max_length=150, verbose_name='Título en Ingles')),
                ('date', models.IntegerField(verbose_name='Año')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Miniatura (220x215)')),
                ('portrait', models.ImageField(upload_to='', verbose_name='Portada (180x270)')),
                ('url', models.CharField(max_length=200, verbose_name='URL Iframe')),
                ('recommended', models.BooleanField(default=False, verbose_name='Recomendada?')),
                ('premiere', models.BooleanField(default=False, verbose_name='Estreno?')),
                ('up_date', models.DateField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='movieapp.Genres', verbose_name='Generos')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['up_date'],
            },
        ),
    ]
