# Generated by Django 3.2.6 on 2021-09-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default=1, max_length=56, verbose_name='País'),
            preserve_default=False,
        ),
    ]
