# Generated by Django 3.2.6 on 2021-09-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_auto_20210904_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url2',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL Opción 2:'),
        ),
        migrations.AddField(
            model_name='movie',
            name='url3',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL Opción SubEng:'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (título entre guiones)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='Miniatura (225x125)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL Opción 1:'),
        ),
    ]
