# Generated by Django 3.2.6 on 2021-09-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_auto_20210905_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=300, verbose_name='URL Opción 1:'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url2',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL Opción 2:'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url3',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL Opción SubEng:'),
        ),
    ]
